### ISSUE TITLE
[BUG] MemorySanitizer: use-of-uninitialized-value

### ISSUE THREAD

**Issue by zlowram** [seladb/PcapPlusPlus#433]
Memory Sanitize report:

```
==543873==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x69b3d0 in std::_Rb_tree<unsigned char, std::pair<unsigned char const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned char const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned char>, std::allocator<std::pair<unsigned char const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_lower_bound(std::_Rb_tree_node<std::pair<unsigned char const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, std::_Rb_tree_node_base*, unsigned char const&) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/stl_tree.h:1928:7
    #1 0x69b1f3 in std::_Rb_tree<unsigned char, std::pair<unsigned char const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned char const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned char>, std::allocator<std::pair<unsigned char const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::lower_bound(unsigned char const&) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/stl_tree.h:1282:16
    #2 0x699e5a in std::map<unsigned char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<unsigned char>, std::allocator<std::pair<unsigned char const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::lower_bound(unsigned char const&) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/stl_map.h:1258:21
    #3 0x694332 in std::map<unsigned char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<unsigned char>, std::allocator<std::pair<unsigned char const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::operator[](unsigned char&&) /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/stl_map.h:515:17
    #4 0x69111b in pcpp::createGtpV1MessageTypeToStringMap[abi:cxx11]() /home/z/self/src/research/pcapplusplus/PcapPlusPlus/Packet++/src/GtpLayer.cpp:449:2
    #5 0x47752a in __cxx_global_var_init /home/z/self/src/research/pcapplusplus/PcapPlusPlus/Packet++/src/GtpLayer.cpp:521:64
    #6 0x4775c4 in _GLOBAL__sub_I_GtpLayer.cpp /home/z/self/src/research/pcapplusplus/PcapPlusPlus/Packet++/./src/GtpLayer.cpp
    #7 0x7b207c in __libc_csu_init (/home/z/self/src/research/pcapplusplus/PcapPlusPlus/Tests/Fuzzers/Bin/FuzzTarget+0x7b207c)
    #8 0x7f2a533f812d in __libc_start_main (/lib64/libc.so.6+0x2712d)
    #9 0x49692d in _start (/home/z/self/src/research/pcapplusplus/PcapPlusPlus/Tests/Fuzzers/Bin/FuzzTarget+0x49692d)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/bin/../lib/gcc/x86_64-redhat-linux/9/../../../../include/c++/9/bits/stl_tree.h:1928:7 in std::_Rb_tree<unsigned char, std::pair<unsigned char const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned char const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned char>, std::allocator<std::pair<unsigned char const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_lower_bound(std::_Rb_tree_node<std::pair<unsigned char const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >
>*, std::_Rb_tree_node_base*, unsigned char const&)
```

Reproducer test case: https://github.com/seladb/PcapPlusPlus/blob/master/Tests/Fuzzers/RegressionTests/regression_samples/crash-63a98d125029876ba4f2e75550382ceffbb251e2

**Comment by seladb** [comment]
I'm not sure why this warning is thrown by the MemorySanitizer. Can you please assist?

**Comment by zlowram** [comment]
I've been taking a look at it and can't really tell why that's happening. After looking around a little bit and reviewing documentation, I think it could be a False Positive due to what is explained [here](https://clang.llvm.org/docs/MemorySanitizer.html#handling-external-code), and [here](https://stackoverflow.com/questions/20617788/using-memory-sanitizer-with-libstdc/20784130#20784130).

Not sure how to tackle this at the moment, though. Maybe it's better to disable regression checks with the MemorySanitizer for the time being and keep UndefinedBehaviorSanitizer and AddressSanitizer. What do you think?

**Comment by seladb** [comment]
Yes I think it makes sense. Can you please do that?

**Comment by seladb** [comment]
PR #434 merged to `master`
