### ISSUE TITLE
The logger printer is not thread safe

### ISSUE THREAD

**Issue by seladb** [seladb/PcapPlusPlus#873]
Running DNS parsing in multi-thread environment results in the following error:

```
==== crash backtrack with gdb =====
 #0  std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str (this=<optimized out>)
    at /usr/include/c++/8/ext/new_allocator.h:86
#1  std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str (this=<optimized out>)
    at /usr/include/c++/8/sstream:639
#2  pcpp::Logger::internalPrintLogMessage (this=0x7ffff7dc8e60 <pcpp::Logger::getInstance()::instance>,
    logLevel=pcpp::Logger::Error, file=0x7ffff7b336e5 "src/DnsLayer.cpp",
    method=0x7ffff7b33850 <pcpp::DnsLayer::parseResources()::__FUNCTION__> "parseResources", line=157) at src/Logger.cpp:52
#3  0x00007ffff7a9b2c8 in pcpp::DnsLayer::DnsLayer (this=0x7fffa05cabb0, data=<optimized out>, dataLen=<optimized out>,
    prevLayer=<optimized out>, packet=<optimized out>, offsetAdjustment=<optimized out>) at src/DnsLayer.cpp:38
#4  0x00007ffff7a97d40 in pcpp::DnsOverTcpLayer::DnsOverTcpLayer (packet=<optimized out>, prevLayer=0x7fffa020e1e0,
    dataLen=44, data=0x7fffa0003bf6 "", this=0x7fffa05cabb0) at ./header/DnsLayer.h:507
#5  pcpp::TcpLayer::parseNextLayer (this=0x7fffa020e1e0) at src/TcpLayer.cpp:375
#6  0x00007ffff7a968b8 in pcpp::Packet::setRawPacket (this=0x7fffaeffc1c0, rawPacket=<optimized out>,
    freeRawPacket=<optimized out>, parseUntil=0, parseUntilLayer=pcpp::OsiModelLayerUnknown) at src/Packet.cpp:80
```

This is because the logger printer is not thread-safe so printing errors might cause a crash

**Comment by seladb** [comment]
The bug was fixed in #877
